version: '3.7'
services:

  react_project:
    build:
      context: ../projects/react_project
      dockerfile: Dockerfile
    volumes:
      - &react_project_folder ./../projects/react_project:/var/www/react_project
      - ./log/react_project:/root/.npm/_logs
      - react_project_node_modules:/var/www/react_project/node_modules
    ports:
      - "8888:8888"
    expose:
      - 8888
    environment:
      - PORT=8888
      - HOST=0.0.0.0
      - REST_API=http://cryptoman.wansiedler.com.loc/api/orders/
    stdin_open: true

#  vuejs_project:
#    build:
#      context: ../projects/vuejs_project
#      dockerfile: Dockerfile
#    volumes:
#      -  ./../projects/vuejs_project:/app
#      - vuejs_project_node_modules:/app/node_modules
#    ports:
#      - "8082:8888"
#    expose:
#      - 8888
#    environment:
#      - PORT=8888
#      - HOST=0.0.0.0
#    stdin_open: true
#
#  angular_project:
#    build:
#      context: ../projects/angular_project
#      dockerfile: Dockerfile
#    volumes:
#      -  ./../projects/angular_project:/app
#      - angular_project_node_modules:/app/node_modules
#    ports:
#      - "8083:4200"
#    expose:
#      - 4200

volumes:
  react_project_node_modules:
  vuejs_project_node_modules:
  angular_project_node_modules: